version: '3'

services:
  product-service:
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - 5001:80

  website:
    build:
      context: ./web
    volumes:
      - ./web:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - product-service